<a href="https://colab.research.google.com/github/sowmith8899/data690_skola2/blob/main/assignment_05/assignment05_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Assignment 05
### Intro to NumPy



#Hands on!

In [43]:
import sys
import numpy as np
import warnings

#Basic Numpy Arrays

In [44]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [45]:
a = np.array([1, 2, 3, 4])


In [46]:
b = np.array([0, .5, 1, 1.5, 2])


In [47]:
a[0], a[1]

(1, 2)

In [48]:
a[0:]

array([1, 2, 3, 4])

In [49]:
a[1:3]

array([2, 3])

In [50]:
a[1:-1]


array([2, 3])

In [51]:
a[::2]


array([1, 3])

In [52]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [53]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [54]:
b[[0, 2, -1]]

array([0., 1., 2.])

#Array Types

In [55]:
a

array([1, 2, 3, 4])

In [56]:
a.dtype

dtype('int64')

In [57]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [58]:
b.dtype

dtype('float64')

In [59]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [60]:
np.array([1, 2, 3, 4], dtype=np.int8)


array([1, 2, 3, 4], dtype=int8)

In [61]:
c = np.array(['a', 'b', 'c'])

In [62]:
c.dtype

dtype('<U1')

In [63]:
d = np.array([{'a': 1}, sys])


In [64]:
d.dtype

dtype('O')

#Dimesnsions and shapes:

In [65]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [66]:
A.shape

(2, 3)

In [67]:
A.ndim

2

In [68]:
A.size

6

In [69]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [70]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [71]:
B.shape


(2, 2, 3)

In [72]:
B.ndim

3

In [73]:
B.size

12

In [74]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [75]:
C.dtype

dtype('O')

In [76]:
C.dtype

dtype('O')

In [77]:
C.size

2

In [78]:
type(C[0])

list

#Indexing and Slicing of Matrices

In [79]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [80]:
A[1]

array([4, 5, 6])

In [81]:
A[1][0]

4

In [82]:
# A[d1, d2, d3, d4]

In [83]:
A[1, 0]

4

In [84]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
A[:, :2]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [86]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [87]:
A[:2, 2:]

array([[3],
       [6]])

In [88]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
A[1] = np.array([10, 10, 10])

In [90]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [91]:
A[2] = 99

In [92]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#Summary statistics

In [93]:
a = np.array([1, 2, 3, 4])

In [94]:
a.sum()

10

In [95]:
a.mean()

2.5

In [96]:
a.std()

1.118033988749895

In [97]:
a.var()

1.25

In [98]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [99]:
A.sum()

45

In [100]:
A.mean()

5.0

In [101]:
A.std()

2.581988897471611

In [102]:
A.sum(axis=0)

array([12, 15, 18])

In [103]:
A.sum(axis=1)

array([ 6, 15, 24])

In [104]:
A.mean(axis=0)

array([4., 5., 6.])

In [105]:
A.mean(axis=1)

array([2., 5., 8.])

In [106]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [107]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

#Broadcasting and Vectorized operations

In [108]:
a = np.arange(4)

In [109]:
a

array([0, 1, 2, 3])

In [110]:
a + 10

array([10, 11, 12, 13])

In [111]:
a * 10

array([ 0, 10, 20, 30])

In [112]:
a

array([0, 1, 2, 3])

In [113]:
a += 100

In [114]:
a

array([100, 101, 102, 103])

In [115]:
l = [0, 1, 2, 3]

In [116]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [117]:
a = np.arange(4)


In [118]:
a

array([0, 1, 2, 3])

In [119]:
b = np.array([10, 10, 10, 10])

In [120]:
b

array([10, 10, 10, 10])

In [121]:
a + b

array([10, 11, 12, 13])

In [122]:
a * b

array([ 0, 10, 20, 30])

#Boolean arrays

In [123]:
a = np.arange(4)

In [124]:
a

array([0, 1, 2, 3])

In [125]:
a[0], a[-1]


(0, 3)

In [126]:
a[[0, -1]]


array([0, 3])

In [127]:
a[[True, False, False, True]]

array([0, 3])

In [128]:
a

array([0, 1, 2, 3])

In [129]:
a >= 2

array([False, False,  True,  True])

In [130]:
a[a >= 2]

array([2, 3])

In [131]:
a.mean()

1.5

In [132]:
a[a > a.mean()]

array([2, 3])

In [133]:
a[~(a > a.mean())]


array([0, 1])

In [134]:
a[(a == 0) | (a == 1)]


array([0, 1])

In [135]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [136]:
A = np.random.randint(100, size=(3, 3))

In [137]:
A

array([[95, 14, 52],
       [36, 19, 97],
       [ 6, 75, 72]])

In [138]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([95, 52, 19,  6, 72])

In [139]:
A > 30

array([[ True, False,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [140]:
A[A > 30]


array([95, 52, 36, 97, 75, 72])

#Linear Algebra

In [141]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [142]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [143]:
A.dot(B)


array([[20, 14],
       [56, 41],
       [92, 68]])

In [144]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [145]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [146]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#Size of objects in Memory

 ## Int, floats

In [148]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [149]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [150]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [151]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [152]:
np.dtype(float).itemsize

8

# Lists are even larger

In [153]:
# A one-element list
sys.getsizeof([1])

80

In [154]:
# An array of one element in numpy
np.array([1]).nbytes

8

#And performance is also important

In [155]:
l = list(range(100000))

In [156]:
a = np.arange(100000)

In [157]:
%time np.sum(a ** 2)

CPU times: user 1.05 ms, sys: 5 µs, total: 1.05 ms
Wall time: 1.07 ms


333328333350000

In [158]:
%time sum([x ** 2 for x in l])

CPU times: user 76.6 ms, sys: 3.55 ms, total: 80.2 ms
Wall time: 93.1 ms


333328333350000

#Useful Numpy functions

##random

In [159]:
np.random.random(size=2)

array([0.77831453, 0.1954507 ])

In [160]:
np.random.normal(size=2)


array([-1.85211756,  0.69901857])

In [161]:
np.random.rand(2, 4)

array([[0.09773843, 0.20897611, 0.87866685, 0.76124425],
       [0.43893461, 0.54316581, 0.31303038, 0.42328002]])

#arrange

In [162]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [164]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#reshape

In [165]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [166]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#Linespace

In [167]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [168]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [169]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

# zeros, ones, empty

In [170]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [171]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [172]:
np.zeros((3, 3), dtype=np.int)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [173]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [174]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [175]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [176]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

#Identity and eye

In [177]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [178]:
np.eye(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [179]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [180]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [181]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [182]:
"Hello World"[6]


'W'