<a href="https://colab.research.google.com/github/sowmith8899/data690_skola2/blob/main/assignment_03/assignment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The Problem:
Write a program that generates 100 random integers between 0 and 9. 

1. Print them in a 10 by 10 matrix neatly arranged like the following (one space between each number):
```
5 1 5 6 2 7 8 6 4 2 
2 3 7 0 6 9 2 4 2 8 
0 0 8 6 4 1 7 2 7 6 
0 1 9 0 0 8 5 8 6 8 
4 1 0 5 5 7 4 6 4 4 
6 0 2 0 1 9 8 2 3 9 
4 0 4 8 1 7 6 6 2 1 
1 7 6 8 5 4 1 9 6 7 
6 4 7 9 9 3 8 2 6 1 
9 0 6 4 0 1 0 6 9 9 
```


In [4]:
import random , numpy as np
li = []
for i in range (0,100) :
  a= random.randint(0,9)
  li.append(a)

x = np.array(li)
shape = (10,10)
mtx = (x.reshape(shape))
print(mtx)


[[3 5 1 8 2 4 6 9 2 6]
 [1 3 3 1 5 0 9 6 2 5]
 [6 9 8 6 3 9 8 7 0 6]
 [4 6 7 6 7 0 1 9 1 6]
 [8 3 3 7 7 7 4 7 2 3]
 [6 9 0 1 9 4 8 4 0 7]
 [4 4 8 1 9 7 8 9 5 0]
 [0 1 1 8 4 3 1 1 9 1]
 [7 2 6 7 7 2 1 0 5 1]
 [3 3 4 8 8 8 8 5 3 0]]
